### ISSUE TITLE
Installation future - move to pypi📦 

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#2112]
Since we've had many questions regarding installation lately, below is where i see freqtrade going in this regards.

## Goal

* Easily installable using a single command (`pip install freqtrade` / `docker pull freqtradeorg/freqtrade`).
* getting setup in another 2-3 commands (`freqtrade create-userdir`, `freqtrade generate-config`(?))

### Steps to reach the goal:

* [x] user_data configurable (#2067)
* [x] move default configuration to user_data directory (#2922)
* [x] move tests out of freqtrade module folder (#2234, #2236)
* [x] copy templates / default configurations when using `freqtrade create-userdir` (to have them available when installing through pip) (#2538 )
* [x] freqtrade subcommand to easily configure a "starter" configuration (similar to `setup.sh`) #2831
* [x] split hyperopt dependencies from `setup.py` (so `pip install freqtrade[hyperopt]` installs hyperopt only dependencies). #2303 
* [ ] having ta-lib as optional dependency (there are other libraries out there, which do mostly the same using numpy/pandas functions only). (further discussion in #2509)
* [x] installable through `pip install freqtrade` 🎉 📦 
* [ ] have documentation point to pypi installability 
* [x] Automated deployment of new releases to pypi #2941
* [x] cleanup installation documentation to have fewer possible routes for installation, which is quite confusing currently
* [ ] remove `setup.sh` since it's not needed anymore

The sequence of these steps is quite flexible - also new steps may be introduced if necessary.

**Comment by hroff-1902** [comment]
Yes, we need move to pypi ASAP! 😆 
Will react in #2067
