### ISSUE TITLE
Strategy validations 

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#2696]
## Problem description

We've seen that the dataframe we pass to the strategy is easy to break by a user if not being careful.
Examples include (but are not limited to):
* [x] Dropping rows from the dataframe (#3107)
* [x] ~Returning resampled dataframe~ (implicitly captured by checking for length)
* [x] adding rows to the dataframe (#3107)
* [x] modifying the dataframe (#3107)
* [x] not adding "buy" column
* [x] not adding "sell" column
* [x]  always returning 0 in the "buy" column
* [x] not returning the dataframe
* [ ] Using a unrealistic stoploss (too tight)
* ...
* ~syntax errors~ (not relevant since syntax-errors will prevent the class from loading, so we cannot run checks on it).

Most of these scenarios are difficult to analyze by inexperienced users - but it should be possible to automate most of that.

Ideally, we'd have a `freqtrade test-strategy` subcommand, which runs a few tests against the strategy and tells the user (before even running backtesting / dry run) if the strategy is formally correct.

this "test_command" could also run on bot startup (optional?) - so we know before the first iteration if the strategy is breaking the dataframe.

it should not run on every iteration, since that would be a waste of resources, and we can assume that if a strategy works once, it'll work again.
