### ISSUE TITLE
Display open trades after backtest period

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#866]
## Proposal of additional backtest functionality

Running backtesting for a specific period will result in X trades completed.
However, it lacks output on how many trades are still open - what the profit/loss on these is.

This hides the fact that some strategies are prone to have stuck trades with -10% for several days/weeks as they are simply eliminated from backtesting results, which only shows completed trades.
  
This becomes especially apparent if compared against external tools as done [here](https://github.com/freqtrade/freqtrade/pull/855#issuecomment-395395877) as part of testing in #855 .

there are multiple ways to tackle this
1. simulate a "force sell" at current rate at the end of the backtest period
2. show open-trades as separate table.

I personally would prefer the 2nd option - however it think the behaviour could be made optional.

## tasks:

- [x] calculate open trades at the end of the backtest period
- [x] show these as part of the output
- [x] include them in extract

**Comment by creslinux** [comment]
Reports should be accurate to be of most use.

Reporting as below bullets covers both 1 and 2 in a single view, its how bitmex reports.
- actual account balance, 
- profit/loss from completed trades
- unrealised profit/loss from open trades (if closed now)

**Comment by xmatthias** [comment]
As #894 was merged, i'll close this ticket.
